### ISSUE TITLE
Status latency

### ISSUE THREAD

**Issue by jtrakk** [kahole/vscode-magit#142]
It feels like Emacs Magit status appears more quickly than edamagit status. I don't have numbers, but I'd guess edamagit takes 20-500 ms longer than Emacs Magit on some open source repos. It would be nice if it happened faster. I'm not sure what the profiling options are for VSCode extensions.

**Comment by kahole** [comment]
First off, yes, Emacs-magit is faster to open the status buffer than edamagit.

What platform are you on? And do you have Forge enabled or not?

I've measured the entry and exit points of the edamagit code for `status`, and on Mac I'm getting on average: `83.42ms`
That number is incomplete though, as it doesn't measure the input lag or the time it takes vscode to fully open the editor (buffer). That number is still much worse than Emacs.

There are a number of things taking time. Inefficient/too many commands to get the complete status of the repo, very little caching of the status commands, VSCode editor management, etc.
I haven't found any silver bullets yet :) But lots of stuff to improve and work on.

**Comment by jtrakk** [comment]
Thanks for checking it out. My info is:

edamagit 0.6.13

> What platform are you on?

Linux

> And do you have Forge enabled or not?

No.

**Comment by pbiggar** [comment]
I've been a heavy user of Magit for about a decade, and I just switch to Edamagit. I definitely concur that it is a lot slower, not just to load status but also refresh the status view after staging or unstaging files and hunks. This is when using it on the same repo that I used Magit on. I definitely prefer using Edamagit, so would be great to get the performance to a similar place!

**Comment by pbiggar** [comment]
I started using a small repo, and noticed that the performance was much better. So this seems related to repo-size.

Repo where things are fast: https://github.com/darklang/tablecloth
Repo where things are slow: https://github.com/darklang/dark

**Comment by kahole** [comment]
@pbiggar Are you able to test commit ab352c9 ? I've improved the performance, but it's not stable for release. I wanna know if it fixes the issue you're seeing with big repos.

(Or should I add a vsix file you can install to your vscode here?)

**Comment by pbiggar** [comment]
@kahole A vsix file would be great, thanks! I don't know how to install otherwise.

**Comment by kahole** [comment]
The vsix is inside the zip here: https://github.com/kahole/edamagit/releases/tag/pre-0.6.19

**Comment by pbiggar** [comment]
After installing I couldn't run `magit status`:

```
[2021-08-05 20:48:39.889] [exthost] [error] TypeError: Cannot read property 'uri' of undefined
    at p (/home/dark/.vscode-server/extensions/kahole.magit-0.6.19/dist/extension.js:1:81651)
    at /home/dark/.vscode-server/extensions/kahole.magit-0.6.19/dist/extension.js:1:75842
    at Array.map (<anonymous>)
    at /home/dark/.vscode-server/extensions/kahole.magit-0.6.19/dist/extension.js:1:75713
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.h [as internalMagitStatus] (/home/dark/.vscode-server/extensions/kahole.magit-0.6.19/dist/extension.js:1:81250)
    at Function.getCurrentMagitRepo (/home/dark/.vscode-server/extensions/kahole.magit-0.6.19/dist/extension.js:1:114880)
    at t.magitStatus (/home/dark/.vscode-server/extensions/kahole.magit-0.6.19/dist/extension.js:1:82299)
    at _executeContributedCommand (/home/dark/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostProcess.js:85:109243) magit.status
```

**Comment by kahole** [comment]
Do you have any renames in your index? Those cause trouble afaik right now.
I'm able to open status for origin/main of dark and run reset `x`  `29e5267` and then stage changes fast.

**Comment by pbiggar** [comment]
No, just a handful of untracked files.

Tried uninstalling and reinstalling from vsix, same issue :(

If you're confident of the changes you could release and I'll try it then?

**Comment by kahole** [comment]
No, it's not stable yet. I just wanted to see if I was on the right track. Could you try latest commit on main of the dark repo. With no other changes in your worktree (tracked or untracked) and then doing a soft reset to ` 29e5267` ? And stage stuff and compare the performance to the stable version in the marketplace?

**Comment by pbiggar** [comment]
Just a checkout in my vscode extensions directory? I'll try that, thanks.

**Comment by kahole** [comment]
I mean testing with the dark repo. And starting from a clean slate (talking about the git state of the dark repo) and doing the steps i mentioned above (in edamagit)

**Comment by pbiggar** [comment]
I tried but I'm not sure how to use the edamagit branch in VSCode. I searched but couldn't find a guide - are there instructions somewhere? I tried just checking out that branch in the .`vscode-server/extensions` directory and that didn't seem to work.

**Comment by kahole** [comment]
I mean ypu should install the vsix I provided, and then do the steps i described.

**Comment by pbiggar** [comment]
Ah, I see. I mentioned [here](https://github.com/kahole/edamagit/issues/142#issuecomment-893786417) that I tried to install the vsix and I got an error (linked above).

**Comment by kahole** [comment]
You are getting an error because the dark repo is in a state that this version of edamagit isn't able to handle yet, as I mentioned. The magit status _is_ the command I've made faster. Since after staging magit status is called to get an updated and correct view of the repo.

**Comment by kahole** [comment]
I also updated the pre-release here: https://github.com/kahole/edamagit/releases/tag/pre-0.6.19
slightly more robust
uninstall and install from vsix after unzipping 👍

**Comment by pbiggar** [comment]
I tried it and it doesn't appear to be any faster. I had a clean status except four untracked files, staging took about a second both with 0.6.19 and 0.6.18.

**Comment by kahole** [comment]
That's interesting. On my mac I'm able to stage and refresh almost instantly with over a 400 active changes in the dark repo. (before the performance enhancement it took like 1 second with that amount of active changes)
Maybe it has to do with platform / docker

**Comment by pbiggar** [comment]
> Maybe it has to do with platform / docker

Quite possible - the code is mounted in docker so it's not at it's prime speed for sure. If you'd like to try, you should be able to open the Dark repo in a remote container on VSCode and see the performance there (docs at https://github.com/darklang/dark/blob/main/docs/vscode-setup.md, though you shouldn't need them, the only thing to note is that VSCode's "clone in container" doesn't work).

**Comment by dandavison** [comment]
I haven't followed all the above conversation but a major problem in large repositories is that edamagit (via the upstream vscode git API) always passes `-u` (Show untracked files) to `git status`. This can be extremely slow in large repos, unless the repo is configured specially to make it efficient.

~~I suggest that edamagit should inspect the existing edamagit option `magit.hide-status-sections` and only add `-u` if `"untracked"` is in there.~~ Actually, `-u` bypasses performance optimizations that might be in place locally such as using watchman and caching untracked files. I suggest that edamagit should never add `-u`: by default untracked files will be returned by `git status` (there's a git config option `status.showUntrackedFiles` that users can set if they wish; not passing `-u` implies that edamagit will respect this option.)

This can be investigated by placing this git wrapper script ahead of your normal git on `$PATH`. The script below "fixes" edamagit by getting rid of the `-u` flag:

```bash
#!/bin/bash -x
start_secs=$(date '+%s')
cmd="$(basename $0) $@"
if [ "$cmd" = "git status -z -u" ]; then
    /PATH/TO/REAL/git status -z
    cmd="$cmd (=> git status -z)"
else
    /PATH/TO/REAL/git "$@"
fi
end_secs=$(date '+%s')
secs=$((end_secs - start_secs))
echo "${secs}s: $cmd" >>/tmp/git.log
```

There's an issue calling for this to be fixed upstream https://github.com/microsoft/vscode/issues/140755, along with a PR https://github.com/microsoft/vscode/pull/140756/files.

**Comment by dandavison** [comment]
If a user has the git config option `status.showUntrackedFiles` set, then magit may be faster than edamagit at showing the status buffer, since magit respects that option: https://github.com/magit/magit/blob/eb14cc7241dc3f52b5b9ad0f8099fbcaf1dec745/lisp/magit-status.el#L760-L781

**Comment by ieugen** [comment]
Fisrt time user of edamagit. 
Status is slow for lots of files. 
I moved a directory with lots of files to another directory (rename)

It took about 15-30 seconds to show magit status window. 
```
Staged changes (1057)
```

**Comment by wittjosiah** [comment]
I can confirm status latency appears to scale with the number of files changed for me. With a small number of changes it's quite quick but when refactoring or merging/rebasing large changes it can get quite slow.

I'm running PopOS (Ubuntu) 22.04 and using Edamagit with VSpaceCode.

**Comment by max-sixty** [comment]
I was on a local wifi connection without connection to the internet (on a flight) and the latency on a tiny repo was a few seconds.

The log had these messages — I'm guessing that something is blocking on a connection and then timing out? I have forge enabled.

[Edit: it seems I forgot to post the messages! But they were a bunch of timeout messages, which blocked for a few seconds before any status was shown]

I don't have that much context on how the extension works (despite being a big fan and proponent of it) — but would it be possible to show the local status without blocking?

**Comment by The-Compiler** [comment]
For me, having forge features enabled makes an enormous difference. With the [qutebrowser repo](https://github.com/qutebrowser/qutebrowser), magit takes around 8s (!) to display the status buffer with `"magit.forge-enabled": true,`, but less than 1s when this is disabled. That's on a stable home WiFi connection. It *might* be a regression somewhere in the last weeks, because I definitely don't remember it being *that* slow, but I haven't worked much on that project for a few weeks.

**Comment by kahole** [comment]
v0.6.36 addresses the forge issue, making it load async at least. So the regular magit status buffer will appear and when the forge data is available, it will refresh and show that.

**Comment by sakshamsharma** [comment]
I'm a bit late to this party but I've been sad about magit being slow for a long time, ever since I moved to VSCode from Emacs. That said, I probably wouldn't have moved to VSCode if not for edamagit, so thanks a ton for this!

I'm going to apologize in advance for what I'm about to release into the world, but I decided to let cursor agent take a stab at speeding it up. It took a few cycles, but it's now much faster for me. I know the code is going to be slop (haven't had the time yet to clean it up), but wanted to share this here in case this helps someone. I did go through various cycles to satisfy my OCDish tendencies and to make sure it behaves the way we're used to.
https://github.com/kahole/edamagit/compare/develop...sakshamsharma:edamagit:develop
The commits are up here. I also made it speed up git commit massively, which was the biggest pain point for me in general. Given this is an open source project I'll probably get around to reviewing the code in a few weeks maybe if someone else doesn't get inspired to do this till then. Until then, happy holidays everyone!
