### ISSUE TITLE
Writing commit message (`c c`), Loading "original-fs" failed 

### ISSUE THREAD

**Issue by mdboom** [kahole/vscode-magit#303]
Recently, I've run into this error when trying to create a commit message (`c c`).

```
Loading "original-fs" failed
Error: Cannot find module 'original-fs'
Require stack:
- /home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at i (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:3:98)
    at r.load (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:2:1637)
    at h.load (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:1:13977)
    at u (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:3:9338)
    at Object.errorback (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:3:9457)
    at h.triggerErrorback (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:1:14271)
    at /home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:1:14022
    at r.load (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:2:1654)
    at h.load (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:1:13977)
    at u (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:3:9338)
    at l._loadModule (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:3:9466)
    at l._resolve (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:4:452)
    at l.defineModule (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:3:5561)
    at Function.p [as define] (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:4:1741)
    at out-build/bootstrap-amd.js (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:4:6445)
    at /home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:1:132
    at Object.<anonymous> (/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js:4:9653)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mdboom/.vscode-server-insiders/bin/bcbdd8e575684d6df1def9a478d645c37129c033/out/server-cli.js'
  ],
  phase: 'loading',
  moduleId: 'original-fs',
  neededBy: [ 'fs' ]
}
Here are the modules that depend on it:
[ 'fs' ]
Aborting commit due to empty commit message.
```

Version: 1.92.0-insider (user setup)
Commit: bcbdd8e575684d6df1def9a478d645c37129c033
Date: 2024-07-25T23:12:28.613Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
edamagit: v0.6.61

This is on Windows, connecting to a WSL "remote".

**Comment by otaviof** [comment]
Same here, but using MacOS and Remote SSH extension 🥺

**Comment by TomasEkeli** [comment]
just started experiencing this - probably a vscode update, as edamagit hasn't changed since spring this year

maybe related? https://github.com/microsoft/vscode-remote-release/issues/188

https://github.com/microsoft/vscode-docs/pull/2632/commits/f35cb2c86a3f840e45b1eab7ad27216108cecaec

**Comment by robert-terbach-gcx** [comment]
i also run into this issue. for me i happens when working in a devcontainer. Stacktrace is the same as from mdboom.

**Comment by mcg** [comment]
FWIW happens on rebasing as well.

**Comment by TomasEkeli** [comment]
i do all my development in devcontainers (or at least wsl or remote), but i tried to commit direct on windows with edamagit - and that still works. 

this makes me suspect the error is within the vscode server?

**Comment by mqvist** [comment]
I'm stuck with this problem with WSL and devcontainers after vscode was updated to v1.92. As mentioned above, the problem seems to be that extensions cannot use the original-fs module when running on the remote server, they should fall back on using fs. A fix for this issue would be greatly appreciated.

**Comment by TomasEkeli** [comment]
while we're waiting for a new release - here's a version i built myself with the fix by @RichardDRJ (putting it here mostly to find it myself when i'm on a different computer)

[magit-0.6.62-beta-commitfix.zip](https://github.com/user-attachments/files/16640955/magit-0.6.62-beta-commitfix.zip)

**Comment by mqvist** [comment]
> while we're waiting for a new release - here's a version i built myself with the fix by @RichardDRJ (putting it here mostly to find it myself when i'm on a different computer)
> 
> [magit-0.6.62-beta-commitfix.zip](https://github.com/user-attachments/files/16640955/magit-0.6.62-beta-commitfix.zip)

Thank you for providing a fixed version, I'm also using it for now. 👍

**Comment by pohlymorph** [comment]
Thanks @TomasEkeli for providing a [fixed pre-release](https://github.com/kahole/edamagit/issues/303#issuecomment-2294102728). I just checked with an installation in a dev container / working remotely and it works for me too:

> Dev Containers Developer: Show All Logs
[2024-08-19T13:02:24.030Z] Dev Containers 0.380.0 over Remote - SSH 0.113.1 in VS Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9).
[...]

> code --list-extensions --show-versions | code -
Extensions installed on Dev Container: xyz @ foo:
[...]
kahole.magit@0.6.62-beta-commitfix

**Comment by v-iashin** [comment]
seems to be fixed now

**Comment by TomasEkeli** [comment]
yes, this was fixed in the most recent release. the issue can be closed

**Comment by robert-terbach-gcx** [comment]
awesome! thanks!
